### ISSUE TITLE
Error in biotype_table_parser.r, wrong input filename from MultiQC

### ISSUE THREAD

**Issue by webermarcolivier** [Flomics/rnaseq#54]
### Description of the bug

In the process flomics_qc_aggregator, the following file cannot be found
```
multiqc_data/mqc_featurecounts_biotype_plot_1.txt
```
when running the script `biotype_table_parser.r`.

All the output files from MultiQC are present in the workdir of the MultiQC process, however the filename have changed, with a different prefix and without the `_1` suffix,
```
multiqc_data/multiqc_featurecounts_biotype_plot.txt
```
I have read in the MultiQC documentation that multiQC adds the `_1` suffix to avoid filename clashes. Because the filename is hard-coded in the `biotype_table_parser.r` script, any changes in output filenames from MultiQC will lead to an error.

Note: I launched a pipeline with test fastq data files with only 10k reads, in the `feature/assembly_hub` branch.

**Comment by ctuni** [comment]
This can be closed as well

**Comment by julienlag** [comment]
Is it fixed? If it is fixed we can close it, but in any case we need to write down a justification here for future reference

**Comment by ctuni** [comment]
This was fixed by changing the file to the correct name. The specific issue regarding the incorrect file name can be closed but a bigger issue remains in this same R script: the biotype names are hardcoded, for which this other [issue](https://github.com/Flomics/fl-rnaseq/issues/3) exists.

This script creates the columns for the biotypes in the "aggregator" process for the QC table, but based on the new way of calculating the biotype breakdown implemented by @julienlag it might become obsolete/suffer radical changes.

I say we can close this issue!

**Comment by julienlag** [comment]
@webermarcolivier what do you say?

**Comment by webermarcolivier** [comment]
I agree, we can close this specific issue, the bigger issue is already described in Flomics/fl-rnaseq#3 .
